# Generated by Django 4.2.2 on 2023-06-15 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_redesocial_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redesocial',
            old_name='whastapp',
            new_name='whatsapp',
        ),
    ]
