# Generated by Django 4.2.2 on 2023-06-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='tipo',
            field=models.CharField(choices=[('CASA', 'Casa'), ('TRABALHO', 'Trabalho'), ('OUTROS', 'Outros')], default='OUTROS', max_length=10),
        ),
    ]
