# Generated by Django 4.2.2 on 2023-06-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusuario',
            name='visivel',
            field=models.BooleanField(default=True),
        ),
    ]
